[package]
name = "to_hevc"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
new_mime_guess = "4.0.1"
mime = "0.3.17"
